/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteView: typeof import('./components/RouteView.vue')['default']
    YAppWrap: typeof import('yun-elp')['YAppWrap']
    YButton: typeof import('yun-elp')['YButton']
    YColumnFilter: typeof import('yun-elp')['YColumnFilter']
    YColumnForm: typeof import('yun-elp')['YColumnForm']
    YColumnOp: typeof import('yun-elp')['YColumnOp']
    YColumnSelect: typeof import('yun-elp')['YColumnSelect']
    YColumnText: typeof import('yun-elp')['YColumnText']
    YDesc: typeof import('yun-elp')['YDesc']
    YDrawer: typeof import('yun-elp')['YDrawer']
    YEcharts: typeof import('yun-elp')['YEcharts']
    YForm: typeof import('yun-elp')['YForm']
    YFormItem: typeof import('yun-elp')['YFormItem']
    YGroupSelect: typeof import('yun-elp')['YGroupSelect']
    YLabel: typeof import('yun-elp')['YLabel']
    YPageFooter: typeof import('yun-elp')['YPageFooter']
    YPageHeader: typeof import('yun-elp')['YPageHeader']
    YPartTitle: typeof import('yun-elp')['YPartTitle']
    YTable: typeof import('yun-elp')['YTable']
    YTableSearch: typeof import('yun-elp')['YTableSearch']
  }
}
